using System;
using Xunit;

namespace Shipwreck.GithubClient.Events
{
    public sealed class MilestoneEventPayloadTest : ActivityPayloadTest
    {
        [Fact]
        public void SampleDataTest()
        {
            var actual = ReadAs<MilestoneEventPayload>("MilestoneEvent.json");
            Assert.Equal(MilestoneAction.Created, actual.Action);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/milestones/3", actual.Milestone.Url);
            Assert.Equal("https://github.com/baxterandthehackers/public-repo/milestones/Test%20milestone%20creation%20webhook%20from%20command%20line2", actual.Milestone.HtmlUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/milestones/3/labels", actual.Milestone.LabelsUrl);
            Assert.Equal(2055681, actual.Milestone.Id);
            Assert.Equal(3, actual.Milestone.Number);
            Assert.Equal("I am a milestone", actual.Milestone.Title);
            Assert.Equal(null, actual.Milestone.Description);
            Assert.Equal("baxterthehacker", actual.Milestone.Creator.Login);
            Assert.Equal(7649605, actual.Milestone.Creator.Id);
            Assert.Equal("https://avatars.githubusercontent.com/u/7649605?v=3", actual.Milestone.Creator.AvatarUrl);
            Assert.Equal("", actual.Milestone.Creator.GravatarId);
            Assert.Equal("https://api.github.com/users/baxterthehacker", actual.Milestone.Creator.Url);
            Assert.Equal("https://github.com/baxterthehacker", actual.Milestone.Creator.HtmlUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/followers", actual.Milestone.Creator.FollowersUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/following{/other_user}", actual.Milestone.Creator.FollowingUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/gists{/gist_id}", actual.Milestone.Creator.GistsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}", actual.Milestone.Creator.StarredUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/subscriptions", actual.Milestone.Creator.SubscriptionsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/orgs", actual.Milestone.Creator.OrganizationsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/repos", actual.Milestone.Creator.ReposUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/events{/privacy}", actual.Milestone.Creator.EventsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/received_events", actual.Milestone.Creator.ReceivedEventsUrl);
            Assert.Equal(AccountType.User, actual.Milestone.Creator.Type);
            Assert.Equal(true, actual.Milestone.Creator.SiteAdmin);
            Assert.Equal(0, actual.Milestone.OpenIssues);
            Assert.Equal(0, actual.Milestone.ClosedIssues);
            Assert.Equal(ItemState.Open, actual.Milestone.State);
            Assert.Equal(DateTimeOffset.Parse("2016/10/07 19:26:08z"), actual.Milestone.CreatedAt);
            Assert.Equal(DateTimeOffset.Parse("2016/10/07 19:26:08z"), actual.Milestone.UpdatedAt);
            Assert.Equal(null, actual.Milestone.DueOn);
            Assert.Equal(null, actual.Milestone.ClosedAt);
            Assert.Equal(70275481, actual.Repository.Id);
            Assert.Equal("public-repo", actual.Repository.Name);
            Assert.Equal("baxterandthehackers/public-repo", actual.Repository.FullName);
            Assert.Equal("baxterandthehackers", actual.Repository.Owner.Login);
            Assert.Equal(4312013, actual.Repository.Owner.Id);
            Assert.Equal("https://avatars.githubusercontent.com/u/4312013?v=3", actual.Repository.Owner.AvatarUrl);
            Assert.Equal("", actual.Repository.Owner.GravatarId);
            Assert.Equal("https://api.github.com/users/baxterandthehackers", actual.Repository.Owner.Url);
            Assert.Equal("https://github.com/baxterandthehackers", actual.Repository.Owner.HtmlUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/followers", actual.Repository.Owner.FollowersUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/following{/other_user}", actual.Repository.Owner.FollowingUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/gists{/gist_id}", actual.Repository.Owner.GistsUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/starred{/owner}{/repo}", actual.Repository.Owner.StarredUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/subscriptions", actual.Repository.Owner.SubscriptionsUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/orgs", actual.Repository.Owner.OrganizationsUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/repos", actual.Repository.Owner.ReposUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/events{/privacy}", actual.Repository.Owner.EventsUrl);
            Assert.Equal("https://api.github.com/users/baxterandthehackers/received_events", actual.Repository.Owner.ReceivedEventsUrl);
            Assert.Equal(AccountType.Organization, actual.Repository.Owner.Type);
            Assert.Equal(false, actual.Repository.Owner.SiteAdmin);
            Assert.Equal(true, actual.Repository.Private);
            Assert.Equal("https://github.com/baxterandthehackers/public-repo", actual.Repository.HtmlUrl);
            Assert.Equal(null, actual.Repository.Description);
            Assert.Equal(false, actual.Repository.Fork);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo", actual.Repository.Url);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/forks", actual.Repository.ForksUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/keys{/key_id}", actual.Repository.KeysUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/collaborators{/collaborator}", actual.Repository.CollaboratorsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/teams", actual.Repository.TeamsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/hooks", actual.Repository.HooksUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/issues/events{/number}", actual.Repository.IssueEventsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/events", actual.Repository.EventsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/assignees{/user}", actual.Repository.AssigneesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/branches{/branch}", actual.Repository.BranchesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/tags", actual.Repository.TagsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/git/blobs{/sha}", actual.Repository.BlobsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/git/tags{/sha}", actual.Repository.GitTagsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/git/refs{/sha}", actual.Repository.GitRefsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/git/trees{/sha}", actual.Repository.TreesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/statuses/{sha}", actual.Repository.StatusesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/languages", actual.Repository.LanguagesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/stargazers", actual.Repository.StargazersUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/contributors", actual.Repository.ContributorsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/subscribers", actual.Repository.SubscribersUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/subscription", actual.Repository.SubscriptionUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/commits{/sha}", actual.Repository.CommitsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/git/commits{/sha}", actual.Repository.GitCommitsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/comments{/number}", actual.Repository.CommentsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/issues/comments{/number}", actual.Repository.IssueCommentUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/contents/{+path}", actual.Repository.ContentsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/compare/{base}...{head}", actual.Repository.CompareUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/merges", actual.Repository.MergesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/{archive_format}{/ref}", actual.Repository.ArchiveUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/downloads", actual.Repository.DownloadsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/issues{/number}", actual.Repository.IssuesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/pulls{/number}", actual.Repository.PullsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/milestones{/number}", actual.Repository.MilestonesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/notifications{?since,all,participating}", actual.Repository.NotificationsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/labels{/name}", actual.Repository.LabelsUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/releases{/id}", actual.Repository.ReleasesUrl);
            Assert.Equal("https://api.github.com/repos/baxterandthehackers/public-repo/deployments", actual.Repository.DeploymentsUrl);
            Assert.Equal(DateTimeOffset.Parse("2016/10/07 19:10:12z"), actual.Repository.CreatedAt);
            Assert.Equal(DateTimeOffset.Parse("2016/10/07 19:10:12z"), actual.Repository.UpdatedAt);
            Assert.Equal(DateTimeOffset.Parse("2016/10/07 19:10:13z"), actual.Repository.PushedAt);
            Assert.Equal("git://github.com/baxterandthehackers/public-repo.git", actual.Repository.GitUrl);
            Assert.Equal("git@github.com:baxterandthehackers/public-repo.git", actual.Repository.SshUrl);
            Assert.Equal("https://github.com/baxterandthehackers/public-repo.git", actual.Repository.CloneUrl);
            Assert.Equal("https://github.com/baxterandthehackers/public-repo", actual.Repository.SvnUrl);
            Assert.Equal(null, actual.Repository.Homepage);
            Assert.Equal(0, actual.Repository.Size);
            Assert.Equal(0, actual.Repository.StargazersCount);
            Assert.Equal(0, actual.Repository.WatchersCount);
            Assert.Equal(null, actual.Repository.Language);
            Assert.Equal(true, actual.Repository.HasIssues);
            Assert.Equal(true, actual.Repository.HasDownloads);
            Assert.Equal(true, actual.Repository.HasWiki);
            Assert.Equal(false, actual.Repository.HasPages);
            Assert.Equal(0, actual.Repository.ForksCount);
            Assert.Equal(null, actual.Repository.MirrorUrl);
            Assert.Equal(0, actual.Repository.OpenIssuesCount);
            Assert.Equal(0, actual.Repository.Forks);
            Assert.Equal(0, actual.Repository.OpenIssues);
            Assert.Equal(0, actual.Repository.Watchers);
            Assert.Equal("master", actual.Repository.DefaultBranch);
            Assert.Equal("baxterandthehackers", actual.Organization.Login);
            Assert.Equal(4312013, actual.Organization.Id);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers", actual.Organization.Url);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers/repos", actual.Organization.ReposUrl);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers/events", actual.Organization.EventsUrl);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers/hooks", actual.Organization.HooksUrl);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers/issues", actual.Organization.IssuesUrl);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers/members{/member}", actual.Organization.MembersUrl);
            Assert.Equal("https://api.github.com/orgs/baxterandthehackers/public_members{/member}", actual.Organization.PublicMembersUrl);
            Assert.Equal("https://avatars.githubusercontent.com/u/4312013?v=3", actual.Organization.AvatarUrl);
            Assert.Equal("", actual.Organization.Description);
            Assert.Equal("baxterthehacker", actual.Sender.Login);
            Assert.Equal(7649605, actual.Sender.Id);
            Assert.Equal("https://avatars.githubusercontent.com/u/7649605?v=3", actual.Sender.AvatarUrl);
            Assert.Equal("", actual.Sender.GravatarId);
            Assert.Equal("https://api.github.com/users/baxterthehacker", actual.Sender.Url);
            Assert.Equal("https://github.com/baxterthehacker", actual.Sender.HtmlUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/followers", actual.Sender.FollowersUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/following{/other_user}", actual.Sender.FollowingUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/gists{/gist_id}", actual.Sender.GistsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}", actual.Sender.StarredUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/subscriptions", actual.Sender.SubscriptionsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/orgs", actual.Sender.OrganizationsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/repos", actual.Sender.ReposUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/events{/privacy}", actual.Sender.EventsUrl);
            Assert.Equal("https://api.github.com/users/baxterthehacker/received_events", actual.Sender.ReceivedEventsUrl);
            Assert.Equal(AccountType.User, actual.Sender.Type);
            Assert.Equal(true, actual.Sender.SiteAdmin);
        }
    }
}